// +build ignore

package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"os"
)

func main() {
	if err := wrapFile("data/providers.json", "assets-autogenerated.go"); err != nil {
		log.Fatal(err)
	}
}

func wrapFile(in, out string) error {
	data, err := ioutil.ReadFile(in)
	if err != nil {
		return err
	}
	of, err := ioutil.TempFile("", "autogenerate-")
	if err != nil {
		return err
	}
	defer of.Close()
	defer os.Remove(of.Name())
	fmt.Fprintf(of, content, data)
	if err := of.Close(); err != nil {
		return err
	}
	return os.Rename(of.Name(), out)
}

const content = `// do not edit, autogenerated

package unfurlist

const providersData = %#q
`
