name: GHCR automatic clean up

on: workflow_dispatch

jobs:
  ghcr-cleanup-job:
      name: GHCR clean up
      runs-on: ubuntu-latest
      steps:
          - name: Checkout actions repository
            uses: actions/checkout@v4
            with:
                repository: Doist/actions
                path: ./.doist/actions
                token: ${{ secrets.GH_REPO_TOKEN }}
          - name: GHCR scan and clean up
            uses: ./.doist/actions/ghcr-cleanup-action
            with:
                package_name: unfurlist
                gh_auth_token: ${{ secrets.GH_PACKAGES_TOKEN }}
                keep_last_number: '2'
                dry_run: true
