name: GHCR automatic clean up

on: workflow_dispatch

jobs:
  ghcr-cleanup-job:
      name: GHCR clean up
      runs-on: ubuntu-latest
      steps:
          - uses: Doist/actions/ghcr-cleanup-action@main
            with:
              package-name: unfurlist
              gh-auth-token: ${{ secrets.GH_PACKAGES_TOKEN }}
              keep-last-number: '2'
              dry-run: true
