name: GHCR automatic clean up

on: 
  schedule:
    - cron: 00 05 1 * * # Runs every 1st of each month at 05:00 UTC 

jobs:
  ghcr-cleanup-job:
      name: GHCR clean up
      runs-on: ubuntu-latest
      steps:
          - name: Checkout actions repository
            uses: actions/checkout@v4
            with:
                repository: Doist/actions
                path: ./.doist/actions
                token: ${{ secrets.GH_REPO_TOKEN }}
          - name: GHCR scan and clean up
            uses: ./.doist/actions/ghcr-cleanup-action
            with:
                package-name: unfurlist
                gh-auth-token: ${{ secrets.GITHUB_TOKEN }}
                keep-last-number: '5'
                dry-run: false
